version: '3'

services:

  webserver:
    image: nginx:latest
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    ports:
      - 80:80
    volumes:
    - ./:/code
    - ./.docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    - ./.docker/nginx/log:/var/log/nginx
    links:
    - php:php
    working_dir: '/code/src/'

  networks:
    static-network:
      ipam:
        config:
          - subnet: 172.20.0.0/16
            #docker-compose v3+ do not use ip_range
            ip_range: 172.28.5.0/24

  php:
    container_name: nette-php
    build: ./.docker/php/
    ports:
    - 1009:9000
    volumes:
    - ./:/code
    - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
    - ./.docker/php/config/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - ./.docker/php/config/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    links:
    - mysql:mysql
    - redis:redis
    working_dir: '/code/src/'

  mysql:
    container_name: nette-mysql
    build: ./.docker/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nette
      MYSQL_USER: nette
      MYSQL_PASSWORD: nette

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  memcached:
    container_name: nette-memcached
    build: ./.docker/memcached
   #image: memcached:latest
    ports:
      - 3307:3307

  redis:
    container_name: nette-redis
    build: ./.docker/redis/
    ports:
    - 6000:6000
    volumes:
    - ./.docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf


